/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisionRouteImport } from './routes/vision'
import { Route as GenerateRouteImport } from './routes/generate'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GenerateRecipeIdRouteImport } from './routes/generate.$recipeId'

const VisionRoute = VisionRouteImport.update({
  id: '/vision',
  path: '/vision',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateRoute = GenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateRecipeIdRoute = GenerateRecipeIdRouteImport.update({
  id: '/$recipeId',
  path: '/$recipeId',
  getParentRoute: () => GenerateRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/generate': typeof GenerateRouteWithChildren
  '/vision': typeof VisionRoute
  '/generate/$recipeId': typeof GenerateRecipeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/generate': typeof GenerateRouteWithChildren
  '/vision': typeof VisionRoute
  '/generate/$recipeId': typeof GenerateRecipeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/generate': typeof GenerateRouteWithChildren
  '/vision': typeof VisionRoute
  '/generate/$recipeId': typeof GenerateRecipeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/chat' | '/generate' | '/vision' | '/generate/$recipeId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/chat' | '/generate' | '/vision' | '/generate/$recipeId'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/generate'
    | '/vision'
    | '/generate/$recipeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  GenerateRoute: typeof GenerateRouteWithChildren
  VisionRoute: typeof VisionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vision': {
      id: '/vision'
      path: '/vision'
      fullPath: '/vision'
      preLoaderRoute: typeof VisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate': {
      id: '/generate'
      path: '/generate'
      fullPath: '/generate'
      preLoaderRoute: typeof GenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate/$recipeId': {
      id: '/generate/$recipeId'
      path: '/$recipeId'
      fullPath: '/generate/$recipeId'
      preLoaderRoute: typeof GenerateRecipeIdRouteImport
      parentRoute: typeof GenerateRoute
    }
  }
}

interface GenerateRouteChildren {
  GenerateRecipeIdRoute: typeof GenerateRecipeIdRoute
}

const GenerateRouteChildren: GenerateRouteChildren = {
  GenerateRecipeIdRoute: GenerateRecipeIdRoute,
}

const GenerateRouteWithChildren = GenerateRoute._addFileChildren(
  GenerateRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  GenerateRoute: GenerateRouteWithChildren,
  VisionRoute: VisionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
